site_name: Backup Teamleader
site_url: https://wertymsd.github.io/manual-backup-crm-teamleader
nav:
  - Inicio:
    - index.md
    - Descarga Gratuita: https://wertymsd.github.io/manual-backup-crm-teamleader/img/centralita_teamleader.zip
  - Sobre Nosotros: 'https://www.linkedin.com/in/%E2%98%85alfonso-martinez-gonzalez%E2%98%85-19236218/'
  - Descarga Gratis: castellano/link-descarga-software-centralita-teamleader.md
  - Español:
    - Guía de uso: castellano/centralita-crm-ia-teamleader.md
    - API Teamleader: castellano/api-teamleader.md
    - Creación de nuevos registros: castellano/creacion-nuevo-registros-teamleader.md
    - Configuración: castellano/pantalla-configuracion-centralita-teamleader.md
    - castellano/App-Call-remoto.md
    - Índices:
      - docs: indice_docs.md
      - castellano: castellano/indice_castellano.md
      - imágenes: img/indice_img.md
      - javascript antiguo: javascripts.old/indice_javascripts.old.md
markdown_extensions:
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      baselevel: 0
theme:
  name: material
  favicon: img/hola.png
  language: es
  features:
    - navigation.footer
    - navigation.tabs
extra_javascript:
    - 'javascripts/removeCredits.js'
plugins:
  - search
  - callouts
  - meta-descriptions:
      export_csv: true
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
extra:
  analytics:
    provider: google
    property: G-5G9B7PZHS4
  consent:
    title: Cookie
    description: >-
      Utilizamos cookies para reconocer sus visitas repetidas y sus preferencias,
      así como para como para medir la eficacia de nuestra documentación y si los
      usuarios  encuentran lo que buscan. Con su consentimiento, nos ayuda a
      mejorar nuestra documentación
